Feature: Recorded User Interaction
  Scenario: User interaction playback
    When I click on "input#search-query"
    When I click on "a"
    When I click on "a"
    When I click on "input#search-query"
    And I input "p" into "input#search-query"
    And I input "pl" into "input#search-query"
    And I input "pli" into "input#search-query"
    And I input "plie" into "input#search-query"
    And I input "plier" into "input#search-query"
    And I input "pliers" into "input#search-query"
    When I click on "button"
    When I click on "img"
    When I click on "button#btn-add-to-cart"
    And I input "01JYR9VAK8H2NFKFCXMBFFBRGF" into "input"
    When I click on "input"
    When I click on "input"
    And I input "01JYR9VAK8H2NFKFCXMBFFBRGG" into "input"
    And I input "01JYR9VAK8H2NFKFCXMBFFBRGH" into "input"
    When I click on "input"
    When I click on "input"
    And I input "01JYR9VAK8H2NFKFCXMBFFBRGJ" into "input"
    When I click on "input"
    And I input "01JYR9VAK8H2NFKFCXMBFFBRGK" into "input"
    And I input "01JYR9VAJPTT40VDM58ZRCMXCV" into "input"
    When I click on "input"
